apiVersion: tekton.dev/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "konflux"
  name: rapidast-check
spec:
  description: >-
    This task uses RapiDAST to scan a running application. Intended for use in an Integration Test, not a build pipeline.
  results:
    - name: TEST_OUTPUT
      description: Tekton task test output.
    - name: SCAN_OUTPUT
      description: RapiDAST scan result.
  params:
    - name: KUBECONFIG_SECRET
      description: The name of a kubeconfig used to to access the test environment.
      type: string
    - name: RAPIDAST_CONFIG_VALUE
      description: The contents of a rapidast config file. Target URLs for scanning should point to localhost and match PORT_FORWARD_TARGETS.
      type: string
    - name: PORT_FORWARD_TARGETS
      description: Scan targets in test environment and arguments for `oc port-forward` commands. Each host:port in RAPIDAST_CONFIG_VALUE requires a respective port-forward target.
      type: array
      default:
        - pod/my-pod 8888:5000
  volumes:
    - name: shared
      emptyDir: {}
  sidecars:
    - name: port-forward
      image: registry.redhat.io/openshift4/ose-cli:latest
      volumeMounts:
        - name: shared
          mountPath: /shared
      env:
        - name: KUBECONFIG
          value: /shared/kubeconfig.yml
        - name: KUBECONFIG_VALUE
          valueFrom:
            secretKeyRef:
              name: "$(params.KUBECONFIG_SECRET)"
              key: kubeconfig
      script: |
        #!/usr/bin/env bash
        set -ex

        cat <<< "$KUBECONFIG_VALUE" > "$KUBECONFIG"
        echo "Wrote kubeconfig for new environment to $KUBECONFIG"

        echo $(params.PORT_FORWARD_TARGETS)

        check_pid_listening_port() {
            local pid=$1
            # checks that PID has at least one local port open
            if lsof -a -p "${pid}" -iTCP -sTCP:LISTEN >/dev/null 2>&1; then
                return 0 # PID has a listening port
            else
                return 1 # PID does not have a listening port
            fi
        }
        
        for t in $(params.PORT_FORWARD_TARGETS[*]); do
          oc port-forward ${t} &
          PID=$!
          timeout 30s check_pid_listening_port ${PID} || {
            echo "oc port-foward failed to open local port"
            exit 1
          }
        done

        touch /shared/port-forward-ready
        sleep infinity

  steps:
    # perform rapidast scan
    - name: rapidast-check
      image: quay.io/konflux-ci/konflux-test:latest
      env:
        - name: KUBECONFIG
          value: /shared/kubeconfig.yml
      volumeMounts:
        - name: shared
          mountPath: /shared
      script: |
        #!/bin/bash
        set -ex

        timeout 5m bash -c 'until [ -f /shared/port-forward-ready ]; do sleep 2; done' || {
          echo "[ERROR] oc port-forward commands in sidecar were not ready in time. Exiting"
          exit 1
        }

        # helper code from konflux-test image, includes handle_error and make_result_json
        source /utils.sh
        trap 'handle_error $(results.TEST_OUTPUT.path)' EXIT

        # Use a here document to write the multiline parameter value to the file.
        # This is the most reliable method for preserving string integrity.
        cat > /tmp/rapidast-config.yaml << EOF
        $(params.RAPIDAST_CONFIG_VALUE)
        EOF

        oc create configmap rapidast-config --from-file=config.yaml=/tmp/rapidast-config.yaml
        # TODO change URL
        oc apply -f https://raw.githubusercontent.com/sfowl/rapidast/refs/heads/k8s-example/examples/kubernetes/rapidast-pod.yaml

        # for debugging
        trap 'oc get pod -o yaml rapidast-check && oc logs rapidast-check -c rapidast' ERR

        # TODO find something better
        sleep 30
        
        oc logs -f rapidast-check -c rapidast
        oc wait --for=jsonpath='{.status.phase}'='Succeeded' pod/rapidast-check --timeout=120s
        oc logs rapidast-check -c results | tee /tmp/rapidast-scan-results.sarif

        # TODO put result handling in separate step

        # Process SCAN_OUTPUT similar to clair scan, but don't use optional 'unpatched_vulnerabilities' field
        scan_result='{"vulnerabilities":{"critical":0, "high":0, "medium":0, "low":0, "unknown":0}, "unpatched_vulnerabilities":{"critical":0, "high":0, "medium":0, "low":0, "unknown":0}}'

        sarif_file="/tmp/rapidast-scan-results.sarif"

        if [ ! -s "$sarif_file" ]; then
          echo "No RapiDAST SARIF file found or it's empty."
          note="Task $(context.task.name) failed: No RapiDAST SARIF file found or it's empty. For details, check Tekton task log."
          TEST_OUTPUT=$(make_result_json -r "ERROR" -t "$note")
          echo "${TEST_OUTPUT}" | tee "$(results.TEST_OUTPUT.path)"
          exit 0
        fi

        # SARIF level mapping: 'error' -> critical, 'warning' -> high, 'note' -> medium.
        result=$(jq -rce \
            '{
                unpatched_vulnerabilities:{
                  critical: ([.runs[0].results[]? | select(.level == "error")] | length // 0),
                  high: ([.runs[0].results[]? | select(.level == "warning")] | length // 0),
                  medium: ([.runs[0].results[]? | select(.level == "note")] | length // 0),
                  low: ([.runs[0].results[]? | select(.level == "none")] | length // 0),
                  unknown: ([.runs[0].results[]? | select(.level == "unknown")] | length // 0)
                }
            }' "$sarif_file")

        scan_result=$(jq -s -rce \
              '.[0].unpatched_vulnerabilities.critical += .[1].unpatched_vulnerabilities.critical |
              .[0].unpatched_vulnerabilities.high += .[1].unpatched_vulnerabilities.high |
              .[0].unpatched_vulnerabilities.medium += .[1].unpatched_vulnerabilities.medium |
              .[0].unpatched_vulnerabilities.low += .[1].unpatched_vulnerabilities.low |
              .[0].unpatched_vulnerabilities.unknown += .[1].unpatched_vulnerabilities.unknown |
              .[0]' <<<"$scan_result $result")

        echo "$scan_result" | tee "$(results.SCAN_OUTPUT.path)"

        note="Task $(context.task.name) completed: Refer to Tekton task result SCAN_OUTPUT for vulnerabilities scanned by RapiDAST."
        TEST_OUTPUT=$(make_result_json -r "SUCCESS" -t "$note")
        echo "${TEST_OUTPUT}" | tee "$(results.TEST_OUTPUT.path)"
