apiVersion: tekton.dev/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "konflux"
  name: rapidast-check
spec:
  description: >-
    This task is for use in an IntegrationTest, to use RapiDAST to scan a running application.
  results:
    - description: Tekton task test output.
      name: TEST_OUTPUT
  params:
    - name: KUBECONFIG_SECRET
      description: The name of a kubeconfig used to to access the test environment.
      type: string
    - name: RAPIDAST_CONFIG_VALUE
      description: The contents of a rapidast config file. Target URLs for scanning should point to localhost and match PORT_FORWARD_TARGETS.
      type: string
    - name: PORT_FORWARD_TARGETS
      description: Scan targets in test environment and arguments for `oc port-forward` commands.
      type: array
      default:
        - pod/my-pod 8888:5000
  volumes:
    - name: credentials
      emptyDir: {}
  steps:
    # setup auth to test env
    - name: get-kubeconfig
      image: quay.io/konflux-ci/konflux-test:latest
      volumeMounts:
        - name: credentials
          mountPath: /credentials
      env:
        - name: KUBECONFIG
          value: /credentials/kubeconfig.yml
        - name: KUBECONFIG_VALUE
          valueFrom:
            secretKeyRef:
              name: "$(params.KUBECONFIG_SECRET)"
              key: kubeconfig
      script: |
        #!/bin/bash
        set -euxo pipefail

        cat <<< "$KUBECONFIG_VALUE" > "$KUBECONFIG"
        echo "Wrote kubeconfig for new environment to $KUBECONFIG"

    # perform rapidast scan
    - name: rapidast-check
      image: quay.io/konflux-ci/konflux-test:latest
      env:
        - name: KUBECONFIG
          value: /credentials/kubeconfig.yml
      volumeMounts:
        - name: credentials
          mountPath: /credentials
      script: |
        #!/bin/bash
        set -ex

        cat <<< "$(params.RAPIDAST_CONFIG_VALUE)" > /tmp/rapidast-config.yaml

        oc create configmap rapidast-config --from-file=config.yaml=/tmp/rapidast-config.yaml
        # TODO change URL
        oc apply -f https://raw.githubusercontent.com/sfowl/rapidast/refs/heads/k8s-example/examples/kubernetes/rapidast-pod.yaml

        # for debugging
        trap 'oc get pod -o yaml rapidast-check && oc logs rapidast-check -c rapidast' EXIT

        # TODO find something better
        sleep 30
        
        oc logs -f rapidast-check -c rapidast
        oc wait --for=jsonpath='{.status.phase}'='Succeeded' pod/rapidast-check --timeout=120s
        oc logs rapidast-check -c results | tee /tmp/rapidast-scan-results.sarif

        # helper code from konflux-test image, includes: parse_test_output
        source utils.sh
        TEST_OUTPUT=
        parse_test_output $(context.task.name) sarif /tmp/rapidast-scan-results.sarif
        echo "${TEST_OUTPUT:-${ERROR_OUTPUT}}" | tee "$(results.TEST_OUTPUT.path)"
        # TODO process results
