apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: testrepo-integration-test
spec:
  params:
    - name: SNAPSHOT
      type: string
      description: |
        For simplicity, we expect a single component inside our snapshot
          {
            "components": [
              {
                "containerImage": "quay.io/example/repo:latest"
              }
            ]
          }
  tasks:
    # we need an clean environment where we have permission to deploy k8s resources
    - name: provision-env
      taskRef:
        params:
          - name: name
            value: eaas-provision-space
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-eaas-provision-space:0.1@sha256:8a344ed61dfeabf741f3f08892414f223ade1849f995da0db172e79c4afc21a3
          - name: kind
            value: task
        resolver: bundles
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)

    # use image from snapshot in new deployment in fresh environment
    - name: deploy-app
      params:
        - name: SNAPSHOT
          value: "$(params.SNAPSHOT)"
      runAfter:
      - provision-env
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
        volumes:
          - name: credentials
            emptyDir: {}
        steps:
          # write the kubeconfig to a volume we can use in subsequent steps
          # and emptyDir volume will be exist for the lifetime of a single taskRun
          - name: get-kubeconfig
            image: quay.io/konflux-ci/konflux-test:latest
            env:
              - name: KUBECONFIG
                value: /credentials/kubeconfig.yml
              - name: KUBECONFIG_VALUE
                valueFrom:
                  secretKeyRef:
                    name: "$(tasks.provision-env.results.secretRef)"
                    key: kubeconfig
            volumeMounts:
              - name: credentials
                mountPath: /credentials
            script: |
              #!/bin/bash
              set -euxo pipefail

              cat <<< "$KUBECONFIG_VALUE" > "$KUBECONFIG"
              echo "Wrote kubeconfig for new environment to $KUBECONFIG"

          # we need to copy the pull secret into our fresh test environment
          # for the SNAPSHOT image stored in a private quay repo
          - name: copy-pull-secret
            image: quay.io/konflux-ci/konflux-test:latest
            env:
              - name: DEST_KUBECONFIG
                value: /credentials/kubeconfig.yml
            volumeMounts:
              - name: credentials
                mountPath: /credentials
            script: |
              #!/bin/bash
              set -euxo pipefail

              oc get secrets test-component-image-pull -o json | jq 'del(.metadata.creationTimestamp,
                .metadata.uid, .metadata.resourceVersion,
                .metadata.annotations."kubectl.kubernetes.io/last-applied-configuration",
                .metadata.namespace)' > /tmp/pull-secret.json
              oc apply --kubeconfig=$DEST_KUBECONFIG -f /tmp/pull-secret.json
              oc link --kubeconfig=$DEST_KUBECONFIG secret --for=pull deployer test-component-image-pull

          - name: deploy-app
            image: quay.io/konflux-ci/konflux-test:latest
            env:
              - name: SNAPSHOT
                value: "$(params.SNAPSHOT)"
              - name: KUBECONFIG
                value: /credentials/kubeconfig.yml
            volumeMounts:
              - name: credentials
                mountPath: /credentials
            script: |
              #!/bin/bash
              set -euxo pipefail

              IMAGE=$(echo "$SNAPSHOT" | jq -r '.components[0].containerImage')
              echo "Extracted image: $IMAGE"

              oc create deployment test-component --image=$IMAGE
              oc get deployment test-component -o yaml
              oc wait --for=condition=Running deployment/test-component --timeout=120s
              # LOGS=$(kubectl logs deployment/test-component
