apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: testrepo-integration-test
spec:
  params:
    - name: SNAPSHOT
      type: string
      description: |
        For simplicity, we expect a single component inside our snapshot
          {
            "components": [
              {
                "containerImage": "quay.io/example/repo:latest"
              }
            ]
          }
  tasks:
    - name: test-component
      params:
        - name: SNAPSHOT
          value: "$(params.SNAPSHOT)"
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
        steps:
          # we need an clean environment where we have permission to deploy k8s resources
          - name: provision-env
            taskRef:
              params:
                - name: bundle
                  value: quay.io/konflux-ci/tekton-catalog/task-eaas-provision-space:0.1@sha256:8a344ed61dfeabf741f3f08892414f223ade1849f995da0db172e79c4afc21a3
                - name: kind
                  value: task
              resolver: bundles
            params:
              - name: ownerName
                value: $(context.pipelineRun.name)
              - name: ownerUid
                value: $(context.pipelineRun.uid)

          # use image from snapshot in new deployment in fresh environment
          - name: deploy-app
            image: quay.io/konflux-ci/konflux-test:latest
            env:
              - name: SNAPSHOT
                value: "$(params.SNAPSHOT)"
              - name: NAMESPACE
                value: "$(context.pipelineRun.namespace)"
              - name: KUBECONFIG_VALUE
                valueFrom:
                  secretKeyRef:
                    name: "$(tasks.provision-env.results.secretRef)"
                    key: kubeconfig
            script: |
              #!/usr/bin/bash
              set -euxo pipefail

              IMAGE=$(echo "$SNAPSHOT" | jq -r '.components[0].containerImage')
              echo "Extracted image: $IMAGE"

              kubectl delete deployment test-component --ignore-not-found
              kubectl create deployment test-component --image=$IMAGE
              kubectl wait --for=condition=Running deployment/test-component --timeout=120s
              # LOGS=$(kubectl logs deployment/test-component -n $NAMESPACE)
